import { Room } from "./Room";
import { Floor, CardType, Orientation } from './EnumTypes';

export class RoomDatabase {
  
  static map: Room[] = [
    new Room("Abandoned Room", Floor.Basement | Floor.Ground, CardType.Omen, Room.fourDoors),
    new Room("Attic", Floor.Upper, CardType.Event, Room.oneDoor),
    new Room("Balcony", Floor.Upper, CardType.Omen, Room.oppositeDoors),
    new Room("Ballroom", Floor.Ground, CardType.Event, Room.fourDoors),
    new Room("Basement Landing", Floor.Basement, CardType.None, Room.fourDoors),
    new Room("Bedroom", Floor.Upper, CardType.Event, Room.oppositeDoors),
    new Room("Bloody Room", Floor.Ground | Floor.Upper, CardType.Item, Room.fourDoors),
    new Room("Catacombs", Floor.Basement, CardType.Omen, Room.oppositeDoors),
    new Room("Chapel", Floor.Ground | Floor.Upper, CardType.Event, Room.oneDoor),
    new Room("Charred Room", Floor.Ground | Floor.Upper, CardType.Omen, Room.fourDoors),
    new Room("Chasm", Floor.Basement, CardType.None, Room.oppositeDoors),
    new Room("Coal Chute", Floor.Ground, CardType.None, Room.oneDoor),
    new Room("Collapsed Room", Floor.Ground | Floor.Upper, CardType.None, Room.fourDoors),
    new Room("Conservatory", Floor.Ground | Floor.Upper, CardType.Event, Room.oneDoor),
    new Room("Creaky Hallway", Floor.Basement | Floor.Ground | Floor.Upper, CardType.None, Room.fourDoors),
    new Room("Crypt", Floor.Basement, CardType.Event, Room.oneDoor),
    new Room("Dining Room", Floor.Ground, CardType.Omen, Room.oppositeDoors),
    new Room("Dusty Hallway", Floor.Basement | Floor.Ground | Floor.Upper, CardType.None, Room.fourDoors),
    new Room("Entrance Hall", Floor.Start, CardType.None, Room.threeDoors, Orientation.East),
    new Room("Foyer", Floor.Start, CardType.None, Room.fourDoors),
    new Room("Furnace Room", Floor.Basement, CardType.Omen, Room.threeDoors),
    new Room("Gallery", Floor.Upper, CardType.Omen, Room.oppositeDoors),
    new Room("Game Room", Floor.Basement | Floor.Ground | Floor.Upper, CardType.Event, Room.threeDoors),
    new Room("Gardens", Floor.Ground, CardType.Event, Room.oppositeDoors),
    new Room("Grand Staircase", Floor.Start, CardType.None, Room.oneDoor, Orientation.West),
    new Room("Graveyard", Floor.Ground, CardType.Event, Room.oneDoor),
    new Room("Gymnasium", Floor.Basement | Floor.Upper, CardType.Omen, Room.oppositeDoors),
    new Room("Junk Room", Floor.Basement | Floor.Ground | Floor.Upper, CardType.Omen, Room.fourDoors),
    new Room("Kitchen", Floor.Basement | Floor.Ground, CardType.Omen, Room.oppositeDoors),
    new Room("Larder", Floor.Basement, CardType.Item, Room.oppositeDoors),
    new Room("Library", Floor.Ground | Floor.Upper, CardType.Event, Room.oppositeDoors),
    new Room("Master Bedroom", Floor.Upper, CardType.Omen, Room.oppositeDoors),
    new Room("Mystic Elevator", Floor.Basement | Floor.Ground | Floor.Upper, CardType.None, Room.oneDoor),
    new Room("Operating Laboratory", Floor.Basement | Floor.Upper, CardType.Event, Room.oppositeDoors),
    new Room("Organ Room", Floor.Basement | Floor.Ground | Floor.Upper, CardType.Event, Room.oppositeDoors),
    new Room("Patio", Floor.Ground, CardType.Event, Room.threeDoors),
    new Room("Pentagram Chamber", Floor.Basement, CardType.Omen, Room.oneDoor),
    new Room("Research Laboatory", Floor.Basement | Floor.Upper, CardType.Event, Room.oppositeDoors),
    new Room("Servants' Quarters", Floor.Basement | Floor.Upper, CardType.Omen, Room.fourDoors),
    new Room("Stairs From Basement", Floor.Basement, CardType.None, Room.oppositeDoors),
    new Room("Statuary Corridor", Floor.Basement | Floor.Ground | Floor.Upper, CardType.Event, Room.oppositeDoors),
    new Room("Storeroom", Floor.Basement | Floor.Upper, CardType.Item, Room.oppositeDoors),
    new Room("Tower", Floor.Upper, CardType.Event, Room.oppositeDoors),
    new Room("Underground Lake", Floor.Basement, CardType.Event, Room.oppositeDoors),
    new Room("Upper Landing", Floor.Start, CardType.None, Room.fourDoors),
    new Room("Vault", Floor.Basement | Floor.Upper, CardType.Event | CardType.Item, Room.oneDoor),
    new Room("Wine Cellar", Floor.Basement, CardType.Item, Room.oppositeDoors)
  ]
} 